//import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from 'next/font/google';

import "./globals.css";
import Header from "./components/Header";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '600'], // Specify the weights you intend to use
  variable: '--font-poppins', // Define a CSS variable for the font
  display: 'swap', // Use 'swap' to ensure text is displayed immediately with a fallback font until Poppins loads
});
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Gossip",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${poppins.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
